[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Маркировка для ui тестов.
    slow: Маркировка для медленных тестов.
    critical: Марикровка для критических тестов.
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для регистрационных тестов.