[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --headed
    --browser=chromium

markers =
    ui: Маркировка для ui тестов.
    slow: Маркировка для медленных тестов.
    critical: Марикровка для критических тестов.
    registration: Маркировка для регистрационных тестов.
    courses: для тестов, связанных с курсами.
    regression: для регрессионных тестов.
    authorization: authorization tests.
